Fix SyntaxError: move global declaration to top of do_GET
Error: 'clients_connect_times' is used prior to global declaration

Cause: Used clients_connect_times before declaring it as global

Fix: Move 'global' declaration to top of do_GET method